---
- name: restart apache2
  service:
    name: apache2
    state: restarted
- name: start httpd service
  service:
    name: httpd
    state: started
  tags: always
#handlers for ubuntu
- name: Reload Apache
  service:
       name: apache2
       state: reloaded

- name: Restart Apache
  service:
       name: apache2
       state: restarted
- name: Restart mysql
  service:
       name: mysql
       state: restarted

